# Generated by Django 5.1.1 on 2024-09-14 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('to_address_line', models.TextField()),
                ('from_address_line', models.TextField()),
                ('pickup_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('max_weight', models.FloatField()),
                ('max_size', models.FloatField()),
                ('delivery_fee', models.FloatField(null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_posts', to=settings.AUTH_USER_MODEL)),
                ('from_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='delivery_posts', to='core.city')),
                ('to_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='pickup_posts', to='core.city')),
            ],
        ),
    ]
