# Generated by Django 5.1.1 on 2024-09-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_from_address_line_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='delivery_fee',
            field=models.FloatField(),
        ),
    ]
