# Generated by Django 5.1.1 on 2024-09-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_delivery_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='delivery_fee',
            field=models.FloatField(null=True),
        ),
    ]
