# Generated by Django 5.1.1 on 2024-09-15 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_rename_city_id_client_city_ids_and_more'),
        ('posts', '0004_alter_post_delivery_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_posts', to='authentication.driver'),
        ),
    ]
