# Generated by Django 5.1.1 on 2024-09-19 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='delivery_commission',
            field=models.FloatField(null=True),
        ),
    ]
