# Generated by Django 5.1.1 on 2024-09-10 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
                ('delivery_address_line', models.CharField(max_length=255)),
                ('pickup_address_line', models.CharField(max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
                ('delivery_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_orders', to='core.city')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.driver')),
                ('pickup_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_orders', to='core.city')),
            ],
        ),
    ]
