# Generated by Django 5.1.1 on 2024-09-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carimage',
            name='image_url',
            field=models.ImageField(upload_to='car_images'),
        ),
        migrations.AlterField(
            model_name='carlicense',
            name='back_image_url',
            field=models.ImageField(upload_to='car_licenses'),
        ),
        migrations.AlterField(
            model_name='carlicense',
            name='front_image_url',
            field=models.ImageField(upload_to='car_licenses'),
        ),
        migrations.AlterField(
            model_name='driverlicense',
            name='back_image_url',
            field=models.ImageField(upload_to='driver_licenses'),
        ),
        migrations.AlterField(
            model_name='driverlicense',
            name='front_image_url',
            field=models.ImageField(upload_to='driver_licenses'),
        ),
        migrations.AlterField(
            model_name='nationalityid',
            name='back_image_url',
            field=models.ImageField(upload_to='nationality_ids'),
        ),
        migrations.AlterField(
            model_name='nationalityid',
            name='front_image_url',
            field=models.ImageField(upload_to='nationality_ids'),
        ),
    ]
