# Generated by Django 5.1.1 on 2024-09-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_carimage_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carimage',
            name='image_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='carlicense',
            name='back_image_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='carlicense',
            name='front_image_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='driverlicense',
            name='back_image_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='driverlicense',
            name='front_image_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='nationalityid',
            name='back_image_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='nationalityid',
            name='front_image_url',
            field=models.TextField(),
        ),
    ]
