# Generated by Django 5.1.1 on 2024-09-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_carimage_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryFEESettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_factor', models.FloatField()),
                ('type_factor', models.FloatField()),
                ('weight_factor', models.FloatField()),
                ('size_factor', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='city',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
