# Generated by Django 5.1.1 on 2024-09-18 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_deliveryfeesettings_city_latitude_city_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carimage',
            name='image_url',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='carlicense',
            name='back_image_url',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='carlicense',
            name='front_image_url',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='driverlicense',
            name='back_image_url',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='driverlicense',
            name='front_image_url',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='nationalityid',
            name='back_image_url',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='nationalityid',
            name='front_image_url',
            field=models.ImageField(upload_to=''),
        ),
    ]
