# Generated by Django 5.1.1 on 2024-09-18 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_carimage_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carlicense',
            name='back_image_url',
            field=models.ImageField(upload_to='Driver_license_images'),
        ),
        migrations.AlterField(
            model_name='carlicense',
            name='front_image_url',
            field=models.ImageField(upload_to='Driver_license_images'),
        ),
        migrations.AlterField(
            model_name='driverlicense',
            name='back_image_url',
            field=models.ImageField(upload_to='Car_license_images'),
        ),
        migrations.AlterField(
            model_name='driverlicense',
            name='front_image_url',
            field=models.ImageField(upload_to='Car_license_images'),
        ),
    ]
