# Generated by Django 5.1.1 on 2024-09-19 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_carlicense_back_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryfeesettings',
            name='commission_percentage',
            field=models.FloatField(default=1),
        ),
    ]
