# Generated by Django 5.1.1 on 2024-09-11 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0003_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
