# Generated by Django 5.1.1 on 2024-09-14 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client'},
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name': 'Driver'},
        ),
    ]
