# Generated by Django 5.1.1 on 2024-09-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_client_phone_number'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='phone_number',
            field=models.ManyToManyField(to='core.phonenumber'),
        ),
    ]
