# Generated by Django 5.1.1 on 2024-09-18 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_client_profile_picture_driver_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='profile_picture',
            field=models.ImageField(upload_to='profile_pictures'),
        ),
    ]
