# Generated by Django 5.1.1 on 2024-09-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_client_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='user_type',
            field=models.CharField(choices=[('DRIVER', 'Driver'), ('CLIENT', 'Client'), ('ADMIN', 'Admin')], default='CLIENT', max_length=10),
        ),
    ]
