# Generated by Django 5.1.1 on 2024-09-19 05:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_arrival_city_order_cargo_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cargo_images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(blank=True, upload_to='cargo_images'), null=True, size=None),
        ),
    ]
