# Generated by Django 5.1.1 on 2024-09-19 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_cargo_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='arrival_city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pickup_city',
        ),
    ]
