# Generated by Django 5.1.1 on 2024-09-19 16:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_arrival_city_remove_order_pickup_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cargo_images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(blank=True, upload_to='cargo_images'), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('rejected', 'Rejected')], default='pending', max_length=16),
        ),
    ]
