# Generated by Django 5.1.1 on 2024-09-19 16:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_cargo_images_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cargo_images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(blank=True, upload_to='cargo_images'), blank=True, default=[';pflke[d['], size=None),
            preserve_default=False,
        ),
    ]
