# Generated by Django 5.1.1 on 2024-09-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_cargo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paymob_order_id',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
